### ISSUE TITLE
Bad logic and has nothing to do with encryption 

### ISSUE THREAD

**Issue by melsaka** [AbdelrhmanSaid/cheatFacebook#2]
The basic idea behind this code is to convert any arabic letter into the same arabic letter with special characters (Vowel Marks and Diacritics), which has nothing to do with encryption and do not achieve the purpose of the code objective, because:

1- special characters like vowel marks and diacritics have a representation code in unicode table.
2- its easy to filter arabic letters from special characters and that what most websites like facebook and google do.
3- it has nothing to do with encryption because it simply do not encrypt anything at all !
4- there is no meaning in encrypting (true encryption methods) your posts and comments on facebook since it is a "Social Network"

**Comment by AbdelrhmanSaid** [comment]
That's not a REAL encryption, Because we need to have the ability to read! All what we want is to cheat Facebook algorithms.

I didn't use Arabic Letters at all, I used Deprecated Letters, Hebrew Vowel Marks and Urdu.

For "س" Letter, I used 3 "ى" to get the same shape "ىىىـ" with different Unicode! 
Also for "أ", I used another deprecated Arabic letter to get the same shape.

At all, I published the whole source to GitHub as you see, You have the ability to edit and PULL as you want.
